config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/sobre-a-lai', to: "pages#sobre_a_lai"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :public_data, only: [:new, :create, :index, :show, :destroy] do
  	resources :comments, only: [:new, :create]
  end
  resources :lai_requests, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    member do
      patch 'submit'
      get 'submit'
    end
    collection do
      get 'city_government_agency_names'
    end
  	resources :request_answers, only: [:new, :create]
  end
  resources :city_government_agencies, only: [ :show ]
end

app/views/shared/_accordion.html.erb
<div id="about-lai">
  <h2>Dúvidas sobre a Lei de Acesso à Informação? Saiba mais!</h2>
  <div id="accordion">
    <div class="card">
      <div class="card-header" id="headingOne">
        <div class="request-js p-3" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          <div class="d-flex justify-content-between">
            <h5 class="mb-0">
              Quem pode entrar com um pedido de acesso a informação?
            </h5>
            <i class="icon-js fas fa-chevron-down"></i>
          </div>
        </div>
      </div>
      <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
        <div class="card-body">
          Qualquer pessoa fisíca ou jurídica. É um direito sei assegurado pela Lei de Acesso a informação. O Art. 5º da lei registra que "É dever do Estado garantir o direito de acesso à informação, que será franqueada, mediante procedimentos objetivos e ágeis, de forma transparente, clara e em linguagem de fácil compreensão."
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header" id="headingTwo">
        <div class="request-js p-3" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          <div class="d-flex justify-content-between">
            <h5 class="mb-0">
              Qual prazo os órgãos responderem ao meu pedido?
            </h5>
            <i class="icon-js fas fa-chevron-down"></i>
          </div>
        </div>
      </div>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
        <div class="card-body">
         O órgão ou entidade terá o prazo máximo de 20 (vinte) dias para disponibilizar a informação requerida. Esse prazo pode ser extendido por mais 10 (dez) dias mediante a justifica expressa, devendo o requerente ser avisado.
       </div>
     </div>
   </div>
   <div class="card">
    <div class="card-header" id="headingThree">
      <div class="request-js p-3" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        <div class="d-flex justify-content-between">
          <h5 class="mb-0">
            E se o órgão não me responder?
          </h5>
          <i class="icon-js fas fa-chevron-down"></i>
        </div>
      </div>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        Você pode apresentar um recurso à autoridade superior no prazo de 10 dias. Se for necessário , é possível recorrer posteriormente à autoridade máxima do órgão. Por fim, se mesmo assim a resposta não for satisfatória, o solicitante pode recorrer à Controladoria Geral de seu Estado.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingFour">
      <div class="request-js p-3" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
        <div class="d-flex justify-content-between">
          <h5 class="mb-0">
            É preciso justificar o pedido de acesso à informação?
          </h5>
          <i class="icon-js fas fa-chevron-down"></i>
        </div>
      </div>
    </div>
    <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
      <div class="card-body">
        Não. De acordo com o art. 10, § 8° da LAI, é proibido exigir que o solicitante informe os motivos de sua solicitação. Entretanto, o órgão/entidade pode dialogar com o cidadão para entender melhor a demanda, de modo a fornecer a informação mais adequada a sua solicitação.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingFive">
      <div class="request-js p-3" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
        <div class="d-flex justify-content-between">
          <h5 class="mb-0">
            Os órgãos são obrigados a fornecer todo e qualquer dado?
          </h5>
          <i class="icon-js fas fa-chevron-down"></i>
        </div>
      </div>
    </div>
    <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordion">
      <div class="card-body">
        Acesso à informação é a regra. Entretanto, são execeções à regra da transparência as informações classificadas como sigilosas. O artigo 25 da Lei regula quais informações podem ser consideradas sigilosas.
      </div>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1560416313-414b33c856a9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=667&q=80);">
  	<div class="container-banner">
	    <h1>Transparência com os dados públicos </h1>
	    <h1>é <span id="banner-typed-text"></span></h1>
	    <p class="mt-3">Incentivando a participação cívica através da LAI</p>
      <div class="search-bar mt-3">
        <%= form_tag public_data_path, method: :get, class: "d-flex justify-content-center" do %>
          <%= text_field_tag :query, params[:query], class: "form-control input", placeholder: "Qual dado público você busca?" %>
          <%= submit_tag "Pesquisar", class: "btn btn-primary" %>
        <% end %>
      </div>
   	</div>
 </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" style="background-color: #363434;">

  <%= link_to root_path, class: "footer-logo" do %>
    <%= image_tag "logo-white.png" %>
  <% end %>

  <div class="footer-links">
  	<a href="mailto:replaibrasil@gmail.com" target="_blank"><i class="far fa-envelope"></i>
  	<a href="https://twitter.com/replaireplai"><i class="fab fa-twitter"></i></a>
  </div>
  <p>Idealizado e desenvolvido no LeWagon © Batch#354</p>
</div>

app/views/shared/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="confirmation" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Seu pedido de acesso a informação foi enviado!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>A repLAI te ajuda a pressionar os órgãos para que você tenha acesso ao que é seu por direito. Dê uma olhada no nosso <%= link_to "twitter", "https://twitter.com/replaireplai", target: "blank" %>  <i class="far fa-smile-wink"></i> !</p>
        <p>Confira o inbox do seu e-mail! Te enviamos uma confirmação com algumas informações relevantes</p> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav-block">
  <div class="navbar navbar-replai">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
    <ul class="navbar-menu">
      <li>
        <%= link_to "Sobre a LAI", sobre_a_lai_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to "Pesquisar dados", public_data_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to "Compartilhar dados", new_public_datum_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to "Criar pedido LAI", new_lai_request_path, class: "nav-link" %>
      </li>
      <li>
       <% if user_signed_in? %>
        <%= link_to "Meus pedidos", lai_requests_path, class: "nav-link" %>
       <% end %>
      </li>
    </ul>
    <% if user_signed_in? %>
      <ul class="navbar-menu" style="list-style: none;">
        <li class="nav-link">
          <p style="margin:0px; font-family: 'Work Sans', 'Helvetica', 'sans-serif'">Olá, <%= current_user.first_name %>!</p>
        </li>
        <li>
          <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    <% else %>
      <div class="navbar-menu" style="list-style: none;">
        <li>
          <%= link_to "Entrar", new_user_session_path, class: "nav-link" %>
        </li>
      </div>
    <% end %>
  </div>
</div>