config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/sobre-a-lai', to: "pages#sobre_a_lai"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :public_data, only: [:new, :create, :index, :show, :destroy] do
  	resources :comments, only: [:new, :create]
  end
  resources :lai_requests, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    member do
      patch 'submit'
      get 'submit'
    end
    collection do
      get 'city_government_agency_names'
    end
  	resources :request_answers, only: [:new, :create]
  end
  resources :city_government_agencies, only: [ :show ]
end

app/models/lai_request.rb
class LaiRequest < ApplicationRecord
  belongs_to :user
  belongs_to :branch
  has_many :request_answers
  validates :status, presence: true, inclusion: { in: %w(Editando Enviado Atrasado Concluído) }
  CATEGORIES = %w[Transparência Financeira Saúde Educação Infraestrutura Segurança]
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  ANONYMITY = [true, false]
  validates :anonymity, inclusion: { in: ANONYMITY }


  attr_accessor :city_government_agency_id
end

app/controllers/lai_requests_controller.rb
class LaiRequestsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_lai_request, only: [:submit, :show, :edit, :update, :destroy]
  include ApplicationHelper

  def index
    @lai_requests = LaiRequest.where(user_id: current_user).order(created_at: :desc)
  end

  def new
    @lai_request = LaiRequest.new
    authorize @lai_request
  end

  def create
    @lai_request = LaiRequest.new(lai_request_params)
    anonymity = params[:anonymity] == "true"
    @lai_request.anonymity = anonymity
    @lai_request.status = "Editando"
    @lai_request.user_id = current_user.id
    authorize @lai_request
    if @lai_request.save
      redirect_to lai_request_path(@lai_request), notice: "Pedido de Acesso à Informação Criado!"
    else
      render :new, notice: "Ops! Faltaram algumas Informações."
    end
  end

  def edit
  end

  def update
    @lai_request.update(lai_request_params)
    redirect_to lai_request_path(@lai_request)
  end

  def destroy
    @lai_request.destroy
    redirect_to lai_requests_path
  end

  def show
  end

  def submit
    unless params[:view]
      # enviar o email pro orgaos fazer depois
      @lai_request.deadline = 20.days.from_now
      @lai_request.status = "Enviado"
      if @lai_request.save!
        render :submit
        send_lai_request(@lai_request.id)
        send_confirmation_email(current_user.id, @lai_request.id)
        if @lai_request.branch.twitter.nil?
          send_tweet(@lai_request.branch.city_government_agency.city_name)
        else
          send_tweet(@lai_request.branch.twitter)
        end
      else
        redirect_to lai_request_path(@lai_request), notice: "you missed something"
      end
    end
  end

  private
  def lai_request_params
    params.require(:lai_request).permit(:description, :category, :format, :title, :anonymity, :branch_id)
  end

  def set_lai_request
    @lai_request = LaiRequest.find(params[:id])
    authorize @lai_request
  end

  def send_confirmation_email(user_id, lai_request_id)
    RequestConfirmationMailer.confirmation(user_id, lai_request_id).deliver_now
  end

  def send_lai_request(lai_request_id)
    RequestConfirmationMailer.send_request(lai_request_id).deliver_now
  end
end

app/views/lai_requests/edit.html.erb
<div class="container-form">
  <h1>Editando seu pedido</h1>

    <%= simple_form_for @lai_request,
        wrapper: :horizontal_form,
        wrapper_mappings: {
        boolean:       :horizontal_boolean,
        check_boxes:   :horizontal_collection,
        date:          :horizontal_multi_select,
        datetime:      :horizontal_multi_select,
        file:          :horizontal_file,
        radio_buttons: :horizontal_collection,
        range:         :horizontal_range,
        time:          :horizontal_multi_select
      } do |f| %>
      <%= f.input :title,
                  label: "Título da Solicitação",
                  :hint => "Seja  breve e preciso. ex: 'Valor Diárias Vereadores Mangaratiba' " %>
      <%= f.input :city_government_agency_id, collection: CityGovernmentAgency.all, label_method: :city_name, value_method: :id, label: "Cidade"%>
      <%= f.association :branch, label_method: :branch_name, value_method: :id, label: "Orgão", wrapper_html: { class: "hidden", id: "branch_wrapper" } %>
      <%= f.input :description,
                  label: "Descrição",
                  :hint => "Adicione uma breve descrição sobre o conjunto de dados que você quer solicitar, especificando o conteúdo e a data em que os dados forem recebidos do poder público." %>
      <%= f.input :category,
                  label: "Categoria",
                  collection: LaiRequest::CATEGORIES %>
      <%= f.input :anonymity, label: "repLAI anônimo?", :as => :boolean %>
      <%= f.input :format,
                  label: "Formato do arquivo" %>
      <%= f.submit "Finalizar formulário", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/lai_requests/index.html.erb
<div class="container-fluid user-dashboard">
  <h1 class="p-5"><span class="text-secondary">Olá, <%= current_user.first_name %>! Esses são seus pedidos:</span><br></h1>

  <div class="row justify-content-center" style="margin:0 200px;">
    <div class="col-12">
      <div id="accordion">
        <% @lai_requests.each_with_index do |request, index| %>
          <div class="card mb-1 card-style">
            <div class="card-header" id="heading<%= index.to_s%>">
              <div class="request-js p-3" data-toggle="collapse" data-target="#collapse<%= index.to_s  %>" aria-expanded="false" aria-controls="collapse<%= index.to_s %>">
                <div>
                  <div class="d-flex justify-content-between">
                    <div>
                      <% unless request.deadline %>
                        <p>Revise antes de enviar!</p>
                      <% end %>
                     <p><%= request.title.truncate(70).capitalize %></p>
                      <% if request.deadline %>
                        <p>Prazo - <%= request.deadline.strftime("%d/%m/%Y") %></p>
                      <% end %>
                    </div>
                    <% if  index == 0 %>
                      <i class="icon-js fas fa-chevron-up"></i>
                    <% else %>
                      <i class="icon-js fas fa-chevron-down"></i>
                    <% end %>
                  </div>

<!--                   <div class="d-flex align-items-center justify-content-end pt-3">
                    <#% if request.status == "Editando" %>
                      <#% if policy(request).edit? %>
                        <#%= link_to edit_lai_request_path(request), class: "far fa-edit mb-1 mr-2 primary", :style=>"" do %>
                        <#% end %>
                      <#% end %>

                      <#% if policy(request).destroy? %>
                        <#%= link_to request, method: :delete, data: { confirm: 'Are you sure?'} do %>
                          <i class="fas fa-trash-alt primary" style=""></i>
                        <#% end %>
                      <#% end %>
                    <#% end %>
                  </div> -->

                </div>

              </div>
            </div>

            <div id="collapse<%= index.to_s  %>" class="<%= index == 0 ? "collapse show" : "collapse" %>" aria-labelledby="heading<%= index.to_s %>" data-parent="#accordion">
              <div class="card-body">
                <p><span style="font-weight: bold;">Município:</span> <%= request.branch.city_government_agency.city_name %></p>
                <p><span style="font-weight: bold;">Orgão:</span> <%= request.branch.branch_name %></p>
                <p><span style="font-weight: bold;">Categoria:</span> <%= request.category %></p>
                <p><span style="font-weight: bold;">Status:</span> <%= request.status %></p>
                <p><span style="font-weight: bold;">Formato do arquivo:</span> <%= request.format %></p>
                <p><span style="font-weight: bold;">Descrição:</span> <%= request.description %></p>
                <div style= "text-align: right">

                    <%= link_to lai_request_path(request), class: "btn btn-primary btn-lg no-print" do %>
                      Ver solicitação
                    <% end %>
                </div>
              </div>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lai_requests/new.html.erb
<div class="container-form">
  <h1>Crie seu Pedido de Acesso à Informação</h1>

    <%= simple_form_for @lai_request,
        wrapper: :vertical_form,
        wrapper_mappings: {
        boolean:       :horizontal_boolean,
        check_boxes:   :horizontal_collection,
        date:          :horizontal_multi_select,
        datetime:      :horizontal_multi_select,
        file:          :horizontal_file,
        radio_buttons: :horizontal_collection,
        range:         :horizontal_range,
        time:          :horizontal_multi_select
      } do |f| %>
      <%= f.input :title,
                  label: "Título",
                  :hint => "Seja  breve e preciso. Ex: 'Valor Diárias Vereadores Mangaratiba' " %>
      <%= f.input :description,
                  label: "Descrição",
                  :hint => "Adicione uma descrição bastante precisa, citando conteúdo, periodicidade e formatação dos dados que deseja. Ex: 'Diárias pagas a vereadores em decorrência de eventos institucionais realizados dos anos de 2017-2019, separados em coluno por nome dos vereadores, valor pago e data do pagamento." %>
      <%= f.input :category,
                  label: "Categoria",
                  collection: LaiRequest::CATEGORIES %>
      <%= f.input :city_government_agency_id, collection: CityGovernmentAgency.all, label_method: :city_name, value_method: :id, label: "Cidade"%>
      <%= f.association :branch, label_method: :branch_name, value_method: :id, label: "Órgão", wrapper_html: { class: "hidden", id: "branch_wrapper" } %>
      <%#= f.input :anonymity, :as => :boolean %>
      <!-- <p>solicitar anonimamente?</p> -->
      <%= f.input :format,
                  label: "Formato do arquivo",
                  collection: ["PDF", "CSV", "XLS", "XLSX", "HTML", "PNG", "GEOJSON", "JSON", "ODS", "TXT", "ZIP"],
                  include_blank: false,
                  include_hidden: false %>
      <div class="container_check">
        <input type="checkbox" id="anonimo_check" name="anonymity" value="true">
        <label class="last-input">Solicitar anonimato</label><br>
      </div>
      <div class="buttons">
        <%= f.submit "Finalizar pedido", class: "btn btn-primary" %>
        <%= f.submit "Cancelar", class: "btn btn-secondary" %>
      </div>
    <% end %>
</div>

app/views/lai_requests/show.html.erb
<div class="container-form">
  <div class="lai-request">
    <h2><%= @lai_request.title %></h2>
    <% if @lai_request.status == "Editando" %>
    <div class="alert-lai">
      <strong>Revise</strong> seu pedido de acesso à informação antes de enviar.
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    </div>
    <% else %>
    <div class="alert-lai">
      Esse é seu seu pedido de acesso à informação enviado.
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    </div>
    <% end %>

    <h3><span class="badge badge-pill badge-secondary">Status:</span>    <%= @lai_request.status %></h3>
    <% unless @lai_request.status == "Editando" %>
      <h3><span class="badge badge-pill badge-secondary">Prazo:</span>   <%= @lai_request.deadline.strftime("%d/%m/%Y") %></h3>
    <% end %>
    
    <h3><span class="badge badge-pill badge-secondary">Descrição do pedido:</span></h3>
    <p ><%= @lai_request.description %></p>

    <h3><span class="badge badge-pill badge-secondary">Município:</span>   <%=@lai_request.branch.city_government_agency.city_name%></h3>
    <h3><span class="badge badge-pill badge-secondary">Órgão:</span>   <%= @lai_request.branch.branch_name  %> </h3>
    <h3 style="padding-bottom: 16px;"><span class="badge badge-pill badge-secondary">Formato:</span>    <%= @lai_request.format %></h3>

    <div style="display:flex;  justify-content: space-between;">
      <div style="text-align: left; font-size:32px; color: white;">
        <%= link_to lai_requests_path do %>
          <i class="fas fa-arrow-circle-left"></i>
        <% end %>

      </div>
      <div style= "text-align: right">
        <% if @lai_request.status == "Editando" %>
        <% if policy(@lai_request).edit? %>
          <% if policy(@lai_request).destroy? %>
          <%= link_to @lai_request, method: :delete, data: { confirm: 'Are you sure?'} do %>
            <i class="fas fa-trash-alt" style="color:black;"></i>
          <% end %>
          <%= link_to edit_lai_request_path(@lai_request), class: "far fa-edit mb-1 mr-2", :style=>"color:black;" do %>
          <% end %>
        <% end %>
        <% end %>
      <% end %>
        <% if @lai_request.status == "Editando" %>
          <%= link_to submit_lai_request_path, method: :patch, class: "btn btn-primary btn-lg no-print" do %>
            Envie sua solicitação
          <% end %>
        <% else %>
          <%= link_to submit_lai_request_path( view: 'visualizar' ), class: "btn btn-primary btn-lg no-print" do %>
            Ver minha solicitação
          <% end %>
        <% end %>
      </div>

    </div>


  </div>

</div>

app/views/lai_requests/submit.html.erb
<div class="my-container">
  <div style="text-align: right;">
    <%= link_to lai_requests_path, class: "btn btn-primary btn-lg no-print" do %>
    Voltar
    <% end %>
    <button class="btn btn-primary btn-lg no-print" id="printPageButton" onClick="window.print();">Salvar</button>

  </div>
  <h2 class="text-center font-weight-bold" style="margin-top: 2em;">PEDIDO DE ACESSO À INFORMAÇÃO CONFORME LEI 12.527 / 2011</h2>

  <h3 style="margin-top: 4em;"> <%= @lai_request.branch.city_government_agency.city_name %>, <%= Time.now.strftime("%d/%m/%Y") %> </h3>
  <br>
  <h3 style="margin-top: 1em;"> Prezada Autoridade Responsável, </h3>
  <br>

  <% unless @lai_request.anonymity == true %>
    <h3 class="text-justify" style="text-indent:100px;margin-top: 2em;"> Eu, <span class="font-weight-bold"><%= @lai_request.user.first_name %> <%= @lai_request.user.last_name %></span>, inscrito no CPF sob o número <span class="font-weight-bold"><%= @lai_request.user.cpf %></span>, com base no artigo 5º (XXXIII) da Constituição
Federal e nos artigos 10, 11 e 12 da Lei nº 12.527/2011 à Lei Geral de Acesso a Informações Públicas, dirijo-me respeitosamente a Vossa Senhoria, com o objetivo de apresentar o seguinte:</h3>
    <br>
  <% else %>
    <h3  class="text-justify" style="text-indent:100px;margin-top: 2em;">A <span class="font-weight-bold">Replai</span>, inscrita no CNPJ sob o <span class="font-weight-bold">nº 12.345.678/0001-90</span>, representada por <span class="font-weight-bold">Silvio Silva Silveira</span>, inscrito no CPF sob o <span class="font-weight-bold">nº 123.123.123-12</span>,com base no artigo 5º (XXXIII) da Constituição Federal e nos artigos 10, 11 e 12 da Lei nº 12.527/2011 à Lei Geral de Acesso a Informações Públicas, dirige-se respeitosamente a Vossa Senhoria, com o objetivo de apresentar o seguinte:</h3>
  <% end %>

<br>
  <h3 class="text-center" style="margin-top: 1em;"> REQUERIMENTO DE INFORMAÇÕES RELACIONADAS A: <br> <span class="font-weight-bold">"<%= @lai_request.title.upcase %></span>"</h3>

    <h3 class="text-justify" style="margin-top: 2em;"> 1. O Requerente solicita o acesso a todos os documentos relacionados a <span class="font-weight-bold"><%= @lai_request.title.downcase %></span>, no formato de arquivo <span class="font-weight-bold"><%= @lai_request.format %></span>, incluindo  mas não se limitando a  as seguintes informações:</h3>

    <h3 class="text-justify" style="text-indent:100px;margin-top: 2em; margin-left: 100px;"><%= @lai_request.description %></h3>
    <br>
    <h3 class="text-justify"> 2. Em cumprimento ao artigo 11 da Lei nº 12.527, de 18 de novembro de 2011, o acesso às informações requisitadas deve ser imediato. Não sendo possível o acesso imediato, a resposta, em conformidade com o referido artigo, deve ser expedida no prazo máximo de 20 (vinte) dias, contados do protocolo deste Requerimento junto a(o) <span class="font-weight-bold"> <%= @lai_request.branch.branch_name %> - <%= @lai_request.branch.city_government_agency.city_name %></span>. Para o recebimento da resposta, comunico o seguinte endereço <span class="font-weight-bold"><%= @lai_request.user.email %></span>.</h3>
<br>


    <h3 style="margin-top: 2em;"> Atenciosamente, </h3>
  <% unless @lai_request.anonymity == true %>
    <h3 class="text-center" style="margin-top: 2em;"> <span class="font-weight-bold"style="border-top:1px solid #000;"> <%= @lai_request.user.first_name %> <%= @lai_request.user.last_name %> </span> </h3>
    <h4 class="text-center" style="padding-top: 0px; font-size:20px;"> CPF - <%= @lai_request.user.cpf %> </h4>
  <% else %>
    <h3 class="text-center" style="margin-top: 2em;"> <span class="font-weight-bold">Replai</span></h3>
    <h4 class="text-center" style="padding-top: 0px; font-size:20px;">CNPJ - 12.345.678/0001-90 </h4>
    <h4 class="text-center" style="padding-top: 0px; font-size:20px;">Representada por: Silvio Silva Siveira (CPF - 123.123.123-12)</h4>
  <% end %>


</div>

<br>
<br>
<br>
<%#= link_to "Ver pdf da nota", "#{nota_path}.pdf", class: "btn btn-primary" %>
<%= render 'shared/modal' %>